### ISSUE TITLE
Comparison with mongoose-sequence

### ISSUE THREAD

**Issue by dandv** [typegoose/auto-increment#6]
Thanks for having a Motivation section! The [vast majority](https://github.com/search?q=comparison+with+author%3Adandv&ref=searchresults&type=Issues&utf8=%E2%9C%93) of projects don't.

Have you looked at @ramiel's [mongoose-sequence](https://github.com/ramiel/mongoose-sequence)? It's well-tested and actively maintained.

**Comment by hasezoey** [comment]
at least since https://github.com/typegoose/typegoose/pull/221 , the main reason why this plugin exists  are:
- to have an plugin that should easily work with typegoose
- testing how to make an mongoose plugin (im still new to this)
- because it was requested, because i didnt find any activly maintained mongoose plugins that incremented values (or id) *without* needing to pass some existingConnection / existingMongoose *before* even adding the plugin to the model
