### ISSUE TITLE
Can auto increment id with `insertMany`?

### ISSUE THREAD

**Issue by Innei** [typegoose/auto-increment#7]
This is my model, but auto increment only worked on `create`, but not working on `insertMany`.

Such as this.
```ts
await this.noteModel.insertMany(models)
```

Only worked this.

```ts
for await (const mo of models) {
      await this.noteModel.create(mo)
    }
```

```ts
@plugin<AutoIncrementIDOptions>(AutoIncrementID, {
  field: 'nid',
  startAt: 1,
})
@plugin(uniqueValidator)
@index({ created: -1 })
@index({ text: 'text' })
@index({ modified: -1 })
@index({ created: -1, modified: -1 })
@index({ nid: -1 })
export default class Note extends BaseCommentIndexModel {
  @prop({ required: false, unique: true })
  public nid: number
}
```

Can you fix it? thank you.

**Comment by hasezoey** [comment]
this plugin currently only operates on the `save` pre hook, `insertMany` will be added in the next release

**Comment by hasezoey** [comment]
currently the plugin only supported hooks for `save`, i have looked into supporting `insertMany` too but discovered that the hook for `insertMany` dosnt provide useful things for the counter (it provides the unprocessed documents that were passed to `insertMany`, means it is an normal POJO instead of an instance of an document and has no `_id` / validation features)

[mongoose-sequence](https://github.com/ramiel/mongoose-sequence/issues/7) had the same problem 

the only workaround is to replace `insertMany` with `create` and take the performance decrease
PS: `model.create` supports an array of documents to be created, you dont need an for-loop (`await this.noteModel.create(models)`)

**Comment by Innei** [comment]
Thank you for your reply.
